#redis: &redis
#adapter: redis
#url: redis://localhost:6379/1
#
#anycable: &anycable
#adapter: anycable

production:
  adapter: redis
  url: redis://localhost:6379/1
development:
  adapter: any_cable
test:
  adapter: any_cable