production:
  clients:
    default:
      database: <%= ENV['DATABASE_NAME'] %>
      hosts:
        - <%= ENV['DATABASE_HOST'] %>
      options:
        user: <%= ENV['DATABASE_USERNAME'] %>
        password:  <%= ENV['DATABASE_PASSWORD'] %>

  options:

test:
  clients:
    default:
      database: ziply_tracking_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

development:
  clients:
    default:
      database: ziply_tracking_development
      hosts:
        - localhost:27017
      options:
